### ISSUE TITLE
In the wild?

### ISSUE THREAD

**Issue by sualko** [otalk/jingle-filetransfer-session#5]
Hey guys,

is this used anywhere, or in other words is this safe to use and is there any example?

**Comment by fippo** [comment]
http://legastero.github.io/jingle-interop-demos/stanzaio/ uses it.
See the test at https://github.com/otalk/jingle.js/blob/master/test/filetransfer.js for an example

**Comment by sualko** [comment]
Thank you for your quick answers. Currently I don't get it working, but I think this dependence on some side effects in my application.

For debugging it would be interesting, which XEP this lib implements. I guess [XEP-0234](http://xmpp.org/extensions/xep-0234.html), but I see no <code><description xmlns='urn:xmpp:jingle:apps:file-transfer:4'></code> block in the offer. And which Jingle transport mechanism are implemented? In-Band Bytestreams? [XEP-0343](http://xmpp.org/extensions/xep-0343.html)?

I would offer to extend the Readme with this information.

**Comment by fippo** [comment]
I think the current implementation is a crippled variant of the :3 version of 0234 with xep-0343 as transport mechanism -- @legastero?

**Comment by sualko** [comment]
3th version of 0234 = In-Band Bytestreams (IBB)

IBB is a transport mechanism, so it could only be IBB or 0343. Before I take a closer look to this, some more information would be very helpful. As you know from previous post, it is very hard for a beginner to understand the complete structure.

As usual, I would create a pull request with a (hopefully) non-crippled variant ;-).

**Comment by sualko** [comment]
Ok, I think I figured it out, which XEP this lib implements. It is an old version of [XEP-0234](http://www.xmpp.org/extensions/tmp/xep-0234-0.14.html). I think it would be a good idea to update it to the current version, because it is much clearer. 

e.g. it includes an indicator that an content element is a file offer. This would fix https://github.com/otalk/jingle.js/blob/master/test/filetransfer.js#L56

**Comment by sualko** [comment]
After I fixed my JXT parsing issue, I get now some red lines in my chrome output.

```
[JINGLE][log:debug] a2799c2e-00a1-4ef5-85dd-b5830ec186fa: session-initiate
[JINGLE][log:info] a2799c2e-00a1-4ef5-85dd-b5830ec186fa: Initiating incoming session
[JINGLE][log:info] a2799c2e-00a1-4ef5-85dd-b5830ec186fa: Changing session state to: pending
[JINGLE][log:error] a2799c2e-00a1-4ef5-85dd-b5830ec186fa: Could not create WebRTC answer
[JINGLE][log:error] Could not process request
```

and a couple of this one

```
Uncaught (in promise) Failed to parse SessionDescription. m= 1 RTP/SAVPF Expects m line.
```

and

```
Uncaught (in promise) Error processing ICE candidate
```

Any idea, where I can report this issue?

**Comment by fippo** [comment]
that looks odd. Can you attach a webrtc-internals dump?

**Comment by sualko** [comment]
I found <code>mandatory: {OfferToReceiveVideo:true, OfferToReceiveAudio:true}</code> in my webrtc-internals, so I guess it is a side effect of my video call lib. Sorry, for that false alarm. This week I have no more time to investigate this, but maybe next week. Thanks a lot for your help, I think we can close this issue.
